replicaCount: 1

image:
  repository: mghannem/mgc
  pullPolicy: Never
  tag: "v1"

service:
  type: ClusterIP
  port: 3000

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: node-app-host
      paths:
        - path: /app
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: []
