apiVersion: v1
kind: Service
metadata:
  name: {{ include "node20-app.fullname" . }}
  labels:
    {{- include "node20-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "node20-app.selectorLabels" . | nindent 4 }}
